### ISSUE TITLE
일반/공인중개사 사용자 별 기능 구현

### ISSUE THREAD

**Issue by xfrnk2** [NezipClover/NezipClover-Backend#4]
백엔드 구현

**Comment by hys0254** [comment]
컨트롤러를 제외한 Dao, Dto, Service 구현 완료

**Comment by hys0254** [comment]
컨트롤러로 post형태의 요청이 들어올때 해당 요청의 데이터를 @ResponseBody 어노테이션을 통해 받게 되면 data를 Json으로 인지하고 데이터를 받게 됨. postman에서 post형태의 http 메세지를 보내고 테스트 하고 싶으면 메세지의 body의 형태를 raw로 설정하고 json 객체를 전송해야 정상적으로 데이터를 보내고 테스트가 가능


참고 : https://chanho0912.tistory.com/20
