### ISSUE TITLE
일반/공인중개사 사용자별 화면 구현

### ISSUE THREAD

**Issue by xfrnk2** [NezipClover/NezipClover-Backend#5]
vue를 이용한 frontend 구현

**Comment by hys0254** [comment]
vue3에서 env 파일 설정
https://jasonwatmore.com/post/2022/05/28/vue-3-vite-access-environment-variables-from-dotenv-env


vue3에서는 vuex 사용법이 조금 다름
composition api를 통해 setup 함수를 통해 한번에 사용하는데 vuex를 제대로 이해하지 못하는 상태에서 이해하기가 매우 힘듬
그래서 아래와 같은 방법을 통해 vuex를 사용함.

vuex 객체를 만들기 위해서는 
index.js에 vuex로부터 {createStore}를 import 하고
필요할 경우 모듈을 import

createStore로 객체를 생성하고 해당 객체를 export


사용할때는
state의 경우 모듈을 '로 감싸주어야됨

mutation의 경우 this.뮤테이션 명이 아닌
this.$store.commit('모듈명/뮤테이션명')과 같이 접근해야 되며

actions의 경우 this.액션명이 아닌
this.$store.dispatch("모듈명/액션명")으로 접근

이게 vue2 에서도 사용되는 방법이 


vue3 vuetify 에서는 v-select 의 @onchange 기능이 없고 @update:modelValue 만  있음
